@header@
@back@
.Sh NAME
.Nm 001-introductions
.Nd A little bit of context.
.Sh DESCRIPTION
This is my first post, so I've called it introductions. But also, I wanted to
give a little bit of context for the existence of this blog.
.Pp
It's not completely true to say that this is my first post, because really I've
had about five distinct first posts. The concept I've had in my mind for what I
wanted this website to be has changed a lot since I first started setting it up
in September of 2025. I think this is largely because what's important to me
has changed a lot too.
.Pp
When I was younger, I always thought I would make a website when I was older,
just like I always thought I would make a career out of being a software
engineer. I started making computers do silly things when I got my first
laptop, and by the time I had my first desktop computer, I was already writing
server mods for Minecraft servers. A website would be a place to host all of my
cool coding projects. It would be an easy place to point to when I wanted to
say,
.Dq hey, look what I made!
.Pp
Fast forward to my career as a software engineer, and my first job was not what
I thought it would be. I didn't know what I wanted when I quit last December,
but I knew that this was not the world of clever people doing clever things I
had imagined when I was a kid. It was a whole lot of bureaucracy, busywork, and
numbers-gaming. If I was very strategic, it was possible for me to make a
direct improvement to the product for end users, based on my intuition for what
users needed. But the corporate system made it very hard to do so, and often
disincentizived the process.
.Pp
As I quit, I asked my colleagues to follow me on my upcoming website. My
colleagues were indeed very clever people, even if the framework we worked
within often didn't allow that to truly shine. I wanted to write about things
that mattered to me, like privacy and consumer rights in technology. It would
host a record of my coding projects, and I'd use it to help me move onto
something new.
.Pp
I kept iterating on the concept for my blog, trying different aesthetics,
writing styles, and deployment techniques. Quickly, I noticed a conflict that
arose between my values and my intentions for the site: I couldn't be
completely honest if I wanted to include my website on my resume.
.Pp
I tried to be half honest, instead. Say what I felt about rampant privacy
violations, government surveillance, unchecked capitalism, and the impact of
big tech monopolies on individual freedoms, but...remain professional. But it
seemed like no matter what I did, I had to erase myself in order to look good
to employers.
.Pp
It was becoming increasingly important to me to wear my values on my chest. At
a similar time, I would realize that I had a nonbinary gender identity, and I
was hearing more and more about the rights and protections of queer people
being threatened worldwide. Many of my friends were scared.
.Pp
So on top of my political disdain for techno-capitalism, it meant a lot to me
to be authentic, as well. To be myself proudly, and let others know it was okay
to do the same. Not to mention, generative AI was spreading through the
software engineering world like a poison, and concerns about its misuse,
effectiveness, and morality were being swept under the carpet in the name of
innovation for shareholders. The message from the industry was clear...use
generative AI, or get out. I chose to get out.
.Pp
In the end, despite the feeling that this would be turning my back on the
corporate world of software, I refused to water myself down to remain
professional. I killed my professional website, and went all-in on my personal
one; the one you're reading now. It really felt like a breath of fresh air to
stop policing my personal expression in the name of professionalism, and it was
obvious to me that this is the right choice for me.
.Pp
To be honest, I still don't have a fixed plan of what weirdfi.sh will be. I
have lots of ideas for fun projects and art that I'd like to make, that I will
share on here. I'll write about my thoughts and feelings on issues that are
important to me, as well as more personal journal-esque entries. But I know now
that whatever I do from now on will be real and true to myself, at all costs.
That's true of my website just as much as my life.
.Pp
And hey, I think I just finished my first post.
.Pp
@back-posts@
.Sh CHANGELOG
.Bl -enum
(2026-08-20) Significantly redrafted contents to have better clarity and focus.
.Sh AUTHORS
Jasper Pine / jaspine
.Sh FOOTNOTES
.Bl -enum 
.Tg authenticity
.It
.Lk ""
There are many people on the internet that write with authenticity, of course,
and a fair few of them have been an inspiration to me over the past four years.
I want to make a more complete list eventually, but for example, I've taken a
great deal of inspiration from
.Lk https://causal.agency https://causal.agency .
It's partly thanks to June, and many others, that this blog exists. Thank you
for being you.
.Lk #b2 ↩
.Tg post
.It
.Lk ""
Yeah, I can do fancy footnotes. Can you tell I've been through a lot of drafts?
.It
.Lk ""
p.s. If you have strong values yourself and work in software, I should say:
your identity in public spheres is a personal choice, and it is partly my
privilege and support network that allows me to throw away job opportunities in
the name of my values. The world will tear you apart if you let it, and there
is no shame in supporting yourself and your loved ones within a capitalist
system. It is not any one person's fault for this situation, except maybe a
handful of billionaires. Please do what is best for you.
.Ed
