@header@
@back@
.Sh NAME
.Nm 001-introductions
.Nd A little bit of context.
.Sh DESCRIPTION
This is my first post, so I've called it introductions. But also, I wanted to
give a little bit of context for the existence of this blog.
.Pp
It's a white lie to call this my first post, because really I've had about five
distinct first posts, none of which left the draft stage. I am a noncommittal
person (there's no doubt about it), but there is more to it than that.
.Pp
I always sort of knew I'd end up making a website, the same way I always knew I
would be a software engineer when I was older. I started making computers do
silly things when I got my first laptop, and by the time I had my first desktop
computer, I was writing modifications for Minecraft servers in Java.
.Pp
A website would serve as an index of all of the cool projects that I would
surely make. Back then, I really was making a new project with every passing
month, even though none of them lost their WIP status. I thought that one day I
would get a handle on my commitment problems with projects, and fill up my
website with them all.
.Pp
Just before I left my job in December, I started telling everyone about my
upcoming website. My colleagues were interested about it, although they
admitted after the dozenth time that I mentioned it, they still didn't know
what would be on it.
.Pp
I had some idea of what would be on it. I cared a lot about privacy, and had
been taking measures to protect my data and reduce my dependency on big tech
companies. I was a couple years into daily driving GrapheneOS on my phone, and
I was spending a lot of time maintaining self-hosted services managed with
NixOS. I planned to weave together these efforts into a series of helpful
tutorials, including supplementary commentary about the wider context for why
you might want to do this stuff.
.Pp
I had always expected my website to be consumable by anybody who was interested
in what I'd been up to. Friends, acquaintances, strangers, and prospective
employers. I quickly noticed I had to restrain myself writing with employers in
mind.
.Pp
I couldn't be too snarky or disdainful about the tech industry or wider
capitalism; this would read as unhinged, unprofessional, and dare I say,
political. I couldn't be too honest about my views on Generative AI, because
most employers are very optimistic about making more money via promised
productivity gains. Further, I had to catch myself from sharing thoughts that
were too vulnerable or outlandish; likewise, this would read as unprofessional.
.Pp
I tried to write within these constraints. I thought I had something that would
work with my final draft in that vein, giving a step-by-step tutorial on how to
use NixOS for self-hosting, presented as an incremental psychotic break. I had
friends read it, and they liked it, but they rightfully noted the satire I was
adding would read as unprofessional. That was the fun part! 
.Pp
In the end, I gave up writing the post half way through, when the goal to
improve my employability lead me to twist a good satire post into a tutorial.
I tried to do three things at once; create an asset I could showcase to
employers as a testament to my skills, write interesting blog posts for fellow
computer enthusiasts who might be interested in what people are doing in the
mystical realm of NixOS, and at the same time, be true to myself and write with
vulnerability.
.Pp
It took me a lot of false starts, but I realized in the end that these three
things were not compatible with each other. I could do write technical blog
that I could show to employers, or a technical blog where I wrote with
authenticity and sincerity, but I could not do all three without compromise on
all fronts.
.Pp
So, I gave up on that version on it, and I decided to let the blog be what I
clearly wanted it to be. This is my plan going forward for WEIRDFI.SH(7).
.Pp
It will messy, sometimes pointless, and too vulnerable in parts, but it will be
me. And I will trust that you, dear Reader, will appreciate that somebody on
the internet is still writing with authenticity, rather than prompting the
Doomdays Device, or the next incarnation of God, or whatever you want to call
it, at $15/1 million tokens.
.Pp
As it always is with me, I can't be certain this will be my final direction.
But I feel pretty good about this right now, despite the fact that this website
might sabotage my career in software. 
.Pp
And hey, I think I just finished my first post. 
.Pp
@back-posts@
.Sh AUTHORS
Jasper / Dylan \(em dcurgz
