@header@
.
.Sh NAME
.Nm Jasper / Dylan
.Nd chronic overthinker, computer enthusiast (they/he)
.Sh SYNPOSIS
.Pp 
I spend most of my time tinkering with computers and playing video games. 
.Pp 
I use Nix for most things, including as a template engine for this blog. This
blog is open-source, along with the rest of my infrastructure.
.Pp
I'm often thinking about moral philosophy and how I can do better. I have
strong values about privacy, security, consumer rights, and personal freedom.
.Pp
Regretably, Valorant is the only reason I use Microsoft Windows. I'm working on
getting all the strawberries in Celeste, which is a great game and you should
play it.
.Pp
I also like plants, though I'm not very good at keeping them alive so far.
.Bd -decorate "aside aside-h" 
.Ed
.Pp
.Lk https://weirdfi.sh/posts posts
\(em
.Lk https://git.weirdfi.sh code
.Ss UPDATES
@updates@
