@header@
.Pp
@back@
.
.Sh NAME
.Nm @title@
.Nd @description@
.Lk @permalink@ (permalink)
.
.Sh DESCRIPTION
.Pp
.Bd -decorate warn
This page is unpublished: I'm still drafting this post. Check back soon!
.Ed
.Bd -decorate aside 
This is a satirical post about a phenomenon I've noticed with Nix. Nix (and
NixOS, nix-darwin, home-manager, etc...) is incredibly powerful software, but
it has a habit of taking over all of your machines, and possibly your entire
life too. You have been warned. ♥
.Ed
.Ss Month 1 - Self-hosting
So maybe you're an Arch Linux user. Maybe you've just installed
__REF{grapheneos GrapheneOS}.
.Dq Wow, what a rush! 
you exclaim to yourself, probably internally. You're acutely aware that your
enthusiasm for privacy most likely presents as paranoid schizophrenia to normal
people. Still, it feels great to claim back some control from the
__REF{panoslopticon panoslopticon},
especially with the ever growing influence of
__REF{technolord_monopolies technolord monopolies}
today.
.Pp
.Dq I should try out self-hosting too,
you start thinking, naturally. I mean, you're no longer using Google Photos,
and you're going to need reliable image backup, right? It can't be that
difficult. It's just some images on a server in the
.Sq cloud ,
whatever that is.
.Pp
You purchase a server, or maybe repurpose that old laptop. It's not dead yet.
Naturally, you're booting straight into your trusty Arch Linux ISO USB stick.
In under
__REF{installation 20 minutes}
you've mounted the drives, formatted the disk partitions, connected to the
network, installed essential packages, tweaked the relevant configuration
files, and successfully provisioned the server.
.Pp
Next, you install
__REF{immich Immich}
— in a container, of course. It's just good form.
Maybe Docker, or Podman if you're feeling anti-establishment that day, or
`systemd-nspawn` if you're feeling manic.
.Pp
With a bit of port forwarding and an Nginx reverse proxy, you have a working
image backup server. But there's a problem: you can only access it at home.
.Pp
So you install
__REF{tailscale Tailscale}
to all of your devices, including your server, and use `tailscale cert` to
generate an SSL certificate for your server's
__REF{magicdns MagicDNS}
endpoint. At this point, you can access your server from anywhere by visiting
.Lk https://example.com https://yourserver.tailXXXXXX.ts.net.
Nice.
.Pp
.Dq What else can I self-host?
you're thinking now. The server is already there. It'd be a waste not to take
advantage of it. What about those local LLMs? Gemma and Qwen seem to be getting
pretty good. Plus, what's the point of all this privacy, anyways, if you're
sending all your data to OpenAI?
.Pp
You setup
__REF{openwebui Open Web UI}
in another container, and spin up an Ollama server.
Nginx needs some tweaks so that you can host both web-apps from the same
endpoint. It still works well.
.Pp
You start setting up more services; some game-servers for friends and family,
other miscellaneous web apps to replace the things you used to rely on Google
for.
.Ss Month 2 - Proper Isolation
A fear starts to creep into the back of your mind. 
.Pp
.Dq Is it safe to host all of these different services on the same machine?
.Pp
Right now, the security boundary between each service is just a container. Each
service shares the same kernel as the host.
__REF{container_escape Container Escape}
is pretty difficult to achieve. But are you __HTML<i>sure</i>__ENDHTML it won't
be an issue? Well...
.Pp -decorate anchor-1
So you start looking into virtual machine orchestration. At this point, used to
your pleasant `podman-tui` niceties (or similar), you look for an equivalent
for virtual machines. Maybe you're wondering if you can setup an interface like
Proxmox or Unraid has, and you settle on
__REF{cockpit Cockpit}
which isn't half bad. And you start provisioning virtual machines manually as
Arch Linux `.qcow2` disk images.
.Bd -decorate "aside aside-1"
You should almost definitely just use Proxmox if you aren't insane, and can
live with your hypervisor running on Debian.
.Ed
.Pp
It works. And if you had any respect for your own time, you'd have stopped
here. Maybe you would setup an automated backup strategy for the `.qcow2`
images, and put a ready-made provisioned VM template image somewhere safe so
you can spin up new VMs easily. Then you could use the next 11 months of time
to develop a new hobby, such as crocheting, and find yourself surrounded by
hundreds of basketball-sized fabric animals by the end of the year. They would
make for good Christmas presents. If only.
.Ss Month 3 - Virtual Machines
.Dq "Isn't this all slightly inefficient?" ,
you think to yourself, with notable disdain for your own perfectionist
tendencies.
.Pp -decorate anchor-2
The boot-time of
.Lk https://www.qemu.org/ QEMU,
as fantastic as it is, mocks you. The systemd journal, and all of those
unnecessary services in each of your VMs, makes you uneasy. The sheer weight of
each VM image, loaded with megabytes of duplicate program configurations and
binaries, keeps you up at night. This simply won't do.
.Bd -decorate "aside aside-2"
You could probably achieve the same effect across traditional virtual machines
with a `virtiofs` mount for `/` on top of
.Lk https://en.wikipedia.org/wiki/ZFS ZFS ,
which supports block-level data deduplication natively. However, this will
incur a performance cost on the host machine, whereas a shared Nix store
approach will perform deduplication "for free" at build time.
.Ed
.Pp
You start researching into MicroVM technologies.
__REF{firecracker Firecracker}
and
__REF{cloud_hypervisor cloud-hypervisor}
stand out for their good support of virtalization kernel primitives and overall
efficiency. A boot-time of a dozen seconds on QEMU can be reduced to just a few
seconds. This is completely unnecessary for your purposes, but this does not
dissaude you.
.Pp
Briefly, you experiment with running other OSes within your imperative
provisioning scheme. Docker is able to utilize images based on
__REF{alpine_linux Alpine Linux}
to keep containerized workloads lean. The same should be possible with virtual
machines, though this will require some work.
.Pp
As you customize your virtual machines further, you start to worry about
something else. The customization effort put into these `.qcow2` images is
completely opaque. It's easy to forget which optimizations you've applied to
each VM image, and which configuration files you've had to change for specific
workloads and why, so much so that you consider recreating all of your images
from scratch just to make sure that you can.
.Pp -decorate anchor-3
The core problem is that at this point they are provisioned manually, and
__REF{imperative_versus_declarative imperatively}.
When you provision manually, it is a substantial effort to re-provision images
when required. When you provision imperatively, the internal state of a given
VM image is unknown, and increasingly so with time. Without careful
consideration and bookkeeping, images can quickly enter an unpredictable state.
.Bd -decorate "aside aside-3"
You can get a lot of the benefit here just by making provision a hands-off
process. For most usecases, it is probably better to use
.Lk https://developer.hashicorp.com/terraform Terraform
or
.Lk https://docs.ansible.com/ Ansible
rather than take a trip down the NixOS rabbit hole.
.Ed
.Pp
Unfortunately, at this point, you learn about NixOS.
.Ss Month 4 - Evaluating NixOS
.Pp
You begin to evaluate NixOS for your usecase.
.Pp -decorate anchor-4
The advantages of switching to NixOS in this case:
.Bl -enum
.It
NixOS allows you to declare a system configuration, such as the set of
customizations previously applied to your Alpine Linux VMs, or the systemd
units that orchestrate your OCI containers, with declarative code. 
.It
NixOS has a rich set of libraries that target service isolation. For example,
OCI containers (Docker and Podman) and `systemd-nspawn` containers can be
trivially declared via the
.Lk https://search.nixos.org/options?channel=unstable&query=oci#show=option%253Avirtualisation.oci-containers.containers virtualisation.oci-containers.containers
option and the
.Lk https://search.nixos.org/options?channel=unstable&query=containers#show=option%253Acontainers.%253Cname%253E.config containers
option respectively.
.It 
Further, the
.Lk https://github.com/microvm-nix/microvm.nix microvm.nix
project allows you to define virtual machines declaratively
-
from the programs and services installed on them, to the vCPUs, memory and
`virtiofs-*` devices that should be allocated and assigned when running them.
The project supports many hypervisors (QEMU, cloud-hypervisor, firecracker,
crosvm, etc...), and will optionally install `microvm-runner` scripts as
systemd services in the host NixOS configuration. These VM images are inner
NixOS installs, which means that configurations and binaries on the host and
the guest machines both live in the Nix store; this allows us to do
deduplication of program binaries across guest images and reclaim disk space.
.It
NixOS is built for and wholeheartedly encourages you to make systems that are
declarative as opposed to imperative. This means that the state of the machine
is always well-known and described by the Nix source code that built it.
.El
.Bd -decorate "aside aside-4"
You can also use the `microvm.nix` library to build virtual machine images as
artifacts that you can export into any virtual machine orchestration tool,
instead of using the `microvm-runner` commands and/or systemd service
integrations, though this will lose the benefit of declaring vCPUs, memory, and
`virtio-*` devices as part of the configuration.
.Ed
.Pp -decorate anchor-5
However, it's not a free lunch, by any means.
.Bl -enum
.It
Nix and NixOS have a steep learning curve. It's not too bad, but in practice,
you will need to commit time and effort to build a sufficient mental model of
Nix: the programming language, the evaluator, activation, the daemon,
derivations and Nix store semantics, the module system. In addition, you must
pick a side;
.Bf -emphasis
stable Nix,
.Ef
where you are required to criticize Flakes on the internet regularly, or
.Bf -emphasis
experimental Nix,
.Ef
where you are required to criticize Flakes on the internet occasionally.
.It
The benefits of NixOS compound as you use it for more and more of your
infrastructure. To fully utilize those benefits, you may choose to use it for
everything. It is a fundamental change in mental model as compared to
traditional Linux distributions, such as Ubuntu, Debian, or Arch Linux. This is
a real disadvantage when you try to install programs and services which weren't
already packaged for Nix by the upstream maintainers or clever Nix enthusiasts.
You may have to understand the functional details of a piece of software to a
ridiculous degree in order to make it work on NixOS.
.It
NixOS comes with its own limitations that are particular to the context in
which it exists; what is easily possible in NixOS depends on its support in
nixpkgs, the package repository for Nix which is maintained by the community.
It is the largest package repository in the world, but it has its limitations.
For example, nearly every option is written with the assumption that you're
running systemd as your process supervisor. In practice, this means you're
going to want to use systemd, and you won't be able to use leaner init systems
like OpenRC under Alpine.
.El
.Bd -decorate "aside aside-5"
Nix flakes are a contentious topic in Nix communities. They are an experimental
feature in upstream Nix, despite being widely used. From what I've seen, most
people can understand why; Nix flakes are poorly implemented in many respects.
But until a group of people come along and push through many proposals and
changesets, carefully thinking about the existing ecosystem which largely acts
like flakes are stable, this is unlikely to change. Many people reject flakes,
and opt for specialized tools instead (like
.Lk https://github.com/andir/npins npins
for dependency pinning) to fulfill specific roles where flakes try to do
everything. This is an issue you will become intimately familiar with if you do
decide to use Nix.
.Ed
.Pp -decorate anchor-6
The results of your evaluation are clear; it sounds cool, but nearly every
person who uses NixOS recommends that you do not use it. This is not
particularly encouraging. However, as an Arch Linux user, the prospect of
challenge and its potential rewards speaks to you, possibly in a very real and
psychotic sense. 
.Pp
You decide to go down the rabbit hole.
.Bd -decorate "aside aside-6"
On the topic of systemd on NixOS, I've heard about
.Lk https://media.ccc.de/v/38c3-sixos-a-nix-os-without-systemd sixos ,
and recently
.Lk https://github.com/finix-community/finix/tree/main finix ,
which are successfully using the
.Lk https://skarnet.org/software/s6/ s6
and
.Lk https://github.com/finit-project/finit finit
supervisors respectively on NixOS. I don't personally know about their
usability at this time. It's encouraging that there's ongoing work in this
space.
.Ed
.Ss ...
.Bd -decorate info
Hey, you've reached the middle of the article, give or take. Thanks for reading
so far.
.Pp
As you've probably guessed, this has been my personal journey finding out about
NixOS, and trying it out for my usecase. Overall, I'm very pleased that I
decided to dive into the deep end roughly 13 months ago.
.Pp
I'll spend the rest of the article giving some examples of NixOS
configurations, and enumerate some techniques I've used that to address issues
that come up in server administration, virtual machine orchestration, and
device management. ♥
.Ed
.Ss ...
.Ss Month 5 - Down the rabbit hole
You hear the advice loud and clear: the benefits of NixOS scale with the amount
that you use it. It's time to re-provision the server.
.Pp
Nix flakes, despite the fact that they're confusingly experimental, seem like
the best bet. Most of the examples you can find seem to use flakes in some capacity.
.Pp
The entrypoint to a Nix flake is the `flake.nix` file. The `flake.nix` file
follows a well-defined schema (for the most part):
.Bd -literal
__HTML
@flake-schema'@__ENDHTML
.Ed
.Sh SEE ALSO
.Bd -decorate aside
You can click on the '↩' to jump back to where you were. ♡
.Ed
.Bl -enum
.Tg grapheneos
.It
.Lk https://grapheneos.org/ GrapheneOS
is an Android fork that removes Google spyware and significantly improves the
security posture of the mobile phone that it runs on.
.Lk #b1 ↩
.Tg panoslopticon
.It
.Lk ""
I can't take credit for this one, and my source(s) prefer to remain unnamed at
this time, despite their impressive knack for encoding dystopia into made up
words.
panoslopticon = slop +
.Lk https://en.wikipedia.org/wiki/Panopticon panopticon .
.Lk #b2 ↩
.Tg technolord_monopolies
.It
See: Google, Apple, Microsoft, Amazon, Meta.
.Lk #b3 ↩
.Tg installation
.It
See:
.Lk https://wiki.archlinux.org/title/Installation_guide The Arch Linux wiki - Installation guide.
.Lk #b4 ↩
.Tg immich
.It
.Lk https://immich.app/ Immich
is a self-hosted photo library. It features neat web- and mobile-apps with
automatic synchronization, and an intuitive, modern UX.
.Lk #b5 ↩
.Tg tailscale
.It
.Lk https://tailscale.com/ Tailscale
is software that automatically configures
secure, encrypted
.Lk https://www.wireguard.com/ Wireguard
tunnels between your devices.
.Lk #b6 ↩
.Tg magicdns
.It
.Lk https://tailscale.com/docs/features/magicdns MagicDNS
is a Tailscale feature that (a) configures a special Tailscale DNS on all of
your devices, and (b) automatically registers domain names for each of your
devices based on their hostnames.
.Lk #b7 ↩
.Tg openwebui
.It
.Lk https://github.com/open-webui/open-webui Open WebUI
is a web-app chat interface for Large Language Models, with support for Ollama,
OpenAI APIs, etc.
.Lk #b8 ↩
.Tg container_escape
.It
.Lk "" 
.Dq Escape to Host (i.e., container escape) enables adversaries to bypass security measures set by virtualized environments, usually allowing them to gain access to the host system’s resources.
—
.Lk https://archive.is/40W9R redcanary.com
.Lk #b9 ↩
.Tg cockpit
.It 
.Lk https://cockpit-project.org/ Cockpit
is a web interface to manage servers, with first-class support for virtual
machines.
.Lk #b10 ↩
.Tg firecracker
.It
.Lk https://firecracker-microvm.github.io/ Firecracker
was developed by Amazon to support their AWS Lambda service. It is a MicroVM
implementation that focuses on blazing fast boot-times (on the order of
milliseconds) and cloud-based workloads.
.Lk #b11 ↩
.Tg cloud_hypervisor
.It
.Lk https://www.cloudhypervisor.org/ cloud-hypervisor
is a MicroVM implementation (a VMM, or Virtual Machine Monitor), that like
Firecracker is designed to support cloud-based workloads efficiently.
.Lk #b12 ↩
.Tg alpine_linux
.It
.Lk https://www.alpinelinux.org/ Alpine Linux
is a minimal Linux distribution. It uses
.Lk https://musl.libc.org/about.html musl libc,
a tiny libc implementation as compared to the traditional glibc, and
.Lk https://wiki.alpinelinux.org/wiki/OpenRC OpenRC
instead of systemd for its init system.
.Lk #b13 ↩
.Tg imperative_versus_declarative
.It
.Lk ""
An imperative programming language is a language where the computer is
instructed step by step. A declarative programming language, on the other hand,
lets you write code that describes what you want, and the computer figures out
how to reach that state. When we talk about computer systems, imperative means
a system where commands and processes update the internal state. A declarative
system, such as in NixOS, has its state declared as a set of rules and
definitions that the computer automatically evaluates.
.Lk #b14 ↩
.El
.Pp
@build-time@
.Pp
@back@
