@header@
.
.Sh NAME
.Nm Dylan Curzon
.Nd Software Engineer (they/he)
.Pp
Hello. I'm a 25-year-old computer enthusiast based in `Leeds, UK`. I've been
writing code for as long as I can remember, but I still have a lot to learn.
I'll be using this space to post about the things I figure out along the way.
.
.Sh SYNPOSIS
.Bd -decorate info
Hey, this blog is brand new! I don't have many posts right now, but I hope
you'll still find something you like, and consider adding my RSS feed to your
feed reader. Thanks for visiting! ♥
.Ed
Welcome to my technical blog, written in
.Lk https://man.openbsd.org/mdoc.7 mdoc(7) 
and powered by
.Lk https://nixos.org/ NixOS .
.Pp
Here's a list of recent posts:
@recent-posts@
.
.Ss LINKS
.Nm GitHub
.Nd
.Lk https://github.com/dcurgz @dcurgz
.Nm RSS
.Nd
.Lk /rss.xml /rss
.
.Ss CONTACT
If you'd like to get in touch, my email address is given below.
@contact@
.
@build-time@
.
@thoughts@
