[[nodes]]
id = "node-1"
runner = "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-node-1"

[[nodes]]
id = "node-2"
runner = "/nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-node-2"

[[nodes]]
id = "node-3"
runner = "/nix/store/cccccccccccccccccccccccccccccccccc-node-3"

[nodes.settings]
auto_create = false
auto_upgrade = false
auto_delete = false
